field.widget.settings.farm_nfa_inline_entity_form_quantity:
  type: mapping
  label: 'Quantity IEF reference display format settings'
  mapping:
    form_mode:
      type: string
      label: "Form mode"
    override_labels:
      type: boolean
      label: "Override labels"
    label_singular:
      type: string
      label: "Label (singular)"
    label_plural:
      type: string
      label: "Label (plural)"
    allow_new:
      type: boolean
      label: "Allow new"
    allow_existing:
      type: boolean
      label: "Allow existing"
    match_operator:
      type: string
      label: "Match operator"
    quantity:
      type: sequence
      label: "Quantity"
      sequence:
          type: sequence
          label: "Quantity"
          sequence:
            type: string
            label: 'Quantity elements'

# Default value.
field.value.farm_nfa_program:
  type: mapping
  label: Default value
  mapping:
    summary:
      type: string
      label: Summary
    description:
      type: text
      label: Description
